Chore runner trm command
RCSS-Tournament-Manager/foxsy-tournament-manager pull request #11
Opened 2024-10-01 03:04 UTC by mroa4

not complete

2024-10-11 23:07 UTC, naderzare requested changes

2024-10-11 23:07 UTC, naderzare commented on runner/app/rabit_mq_app.py
> +
I think it should be after async with message.process(ignore_processed=True):

also there is another solution:
we can use get_nowait instead of get
then we can handle commands here instead of handle_***
so we do not need use 
        while True:
            async with self.lock:
                if not self.games:
                    break
            await asyncio.sleep(2)  # Wait before checking again

2024-10-11 23:07 UTC, naderzare commented on tournament_manager2/app/managers/runner_manager.py
> +            log = RunnerLogModel(
we should use runner log model, when runner wants to log something

2024-10-11 23:07 UTC, naderzare commented on tournament_manager2/app/managers/runner_manager.py
> +            log = RunnerLogModel(
remove

2024-10-11 23:07 UTC, naderzare commented on tournament_manager2/app/managers/runner_manager.py
> +    async def mark_resume_runner(self, runner_id: int) -> ResponseMessage:
where do you use this function?

2024-10-12 01:02 UTC, mroa4 commented on tournament_manager2/app/managers/runner_manager.py
> +    async def mark_resume_runner(self, runner_id: int) -> ResponseMessage:
removed - it was just another way of implementing it

2024-10-12 01:03 UTC, mroa4 commented on runner/app/game_runner/runner_manager.py
> +        self.status = "running"
Done

2024-10-12 02:14 UTC, mroa4 commented on tournament_manager2/app/fast_api_app.py
> +            print(command_request.command)
removed

2024-10-12 03:47 UTC, mroa4 commented on tournament_manager2/app/fast_api_app.py
> +        @self.app.post("/runner/send_command", response_model=ResponseMessage, tags=["Runner Management"])
- If runner_ids is None, the command is sent to all runners.
- If runner_ids is an int or a list of ints, the command is sent to that specific runners.
- If runner_ids is empty or contains invalid IDs, appropriate errors are returned.

2024-10-12 03:47 UTC, mroa4 commented on tournament_manager2/app/managers/runner_manager.py
> +    RunnerStatusMessageEnum,
Done

2024-10-12 03:47 UTC, mroa4 commented on tournament_manager2/app/managers/runner_manager.py
> +            #     channel = await connection.channel()
Done, this was the other method

2024-10-12 03:48 UTC, mroa4 commented on runner/app/fast_api_app.py
> +            # print(f'GameRunnerManager receive_command:{command_request}')
There is no logger in runner side - do you want me to add it?

2024-10-12 03:49 UTC, mroa4 commented on tournament_manager2/app/managers/runner_manager.py
> +            log = RunnerLogModel(
Removed

2024-10-12 04:49 UTC, mroa4 commented on runner/app/utils/messages.py
> +    STOPPING = 'stopping'
removed stopping

2024-10-12 16:35 UTC, mroa4 commented on runner/app/rabit_mq_app.py
> +
doesn't it make some other problems like some messages might not be processed or it does more requests so more power usage and we need an extra error handling if there is no msg (queue being empty - try except)

having handle_*** isn't it better? like it's more modular.

2024-10-12 16:36 UTC, mroa4 commented on runner/app/utils/messages.py
> +    STOPPING = 'stopping'
Removed

2024-10-12 17:22 UTC, mroa4 commented on tournament_manager2/app/managers/runner_manager.py
> +            log = RunnerLogModel(
Moved to runner side

2024-10-12 17:23 UTC, mroa4 commented on tournament_manager2/app/managers/runner_manager.py
> +            runner = runner_response  # Type: GetRunnerResponseMessage
Fixed

2024-10-12 17:34 UTC, mroa4 commented on runner/app/fast_api_app.py
> +            # print(f'GameRunnerManager receive_command:{command_request}')
Added

2024-10-12 17:38 UTC, mroa4 commented on tournament_manager2/app/managers/runner_manager.py
> +            log = RunnerLogModel(
Moved to runner side

2024-10-12 18:38 UTC, mroa4 commented on runner/app/rabit_mq_app.py
> +
did it new branch for it **[feat_pause_command_event](https://github.com/RCSS-Tournament-Manager/foxsy-tournament-manager/tree/feat_pause_command_event)**

2024-10-16 20:14 UTC, merged